const oracledb = require('oracledb');
const fs = require('fs');
const path = require('path');

async function run() {
    let connection;

    try {
        connection = await oracledb.getConnection({
            user: 'C##Zakat',
            password: 'zakat123',
            connectString: 'localhost:1521/XE'
        });

        console.log('Connected to database');

        const sqlPath = path.join(__dirname, '../database/system_logs.sql');
        const sqlContent = fs.readFileSync(sqlPath, 'utf8');

        // Split by '/' which handles the PL/SQL blocks and separates them from the table creation
        // The table creation is at the top. We need to be careful.
        // My file format:
        // CREATE TABLE ...;
        //
        // -- 2. Triggers
        //
        // CREATE ... TRIGGER ... END;
        // /
        // ...

        // Strategy: Split by '/' first to separate triggers. 
        // The first chunk will contain the CREATE TABLE statement (ending in ;) and the first Trigger body.
        // Wait, standard SQL clients splits by / on a new line.

        // Let's rely on a simpler regex to find the statements. 
        // Actually, since I control the file, I know:
        // 1. "CREATE TABLE SYSTEM_LOGS ... );" 
        // 2. "CREATE OR REPLACE TRIGGER TRG_LOG_USERS ... END;"
        // 3. "CREATE OR REPLACE TRIGGER TRG_LOG_DONATIONS ... END;"
        // 4. "CREATE OR REPLACE TRIGGER TRG_LOG_BENEFICIARIES ... END;"

        // Let's hardcode the executions to be safe, reading the file is good but parsing is error-prone.
        // I'll just execute the known statements for reliability.

        console.log('Creating SYSTEM_LOGS table...');
        try {
            await connection.execute(`
                CREATE TABLE SYSTEM_LOGS (
                    LOG_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    TABLE_NAME VARCHAR2(50) NOT NULL,
                    ACTION_TYPE VARCHAR2(20) NOT NULL,
                    RECORD_ID NUMBER,
                    ACTION_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    DETAILS VARCHAR2(4000)
                )
            `);
            console.log('Table SYSTEM_LOGS created.');
        } catch (e) {
            if (e.message.includes('ORA-00955')) {
                console.log('Table SYSTEM_LOGS already exists.');
            } else {
                throw e;
            }
        }

        const triggers = [
            {
                name: 'TRG_LOG_USERS',
                sql: `
                CREATE OR REPLACE TRIGGER TRG_LOG_USERS
                AFTER INSERT OR UPDATE OR DELETE ON USERS_PUBLIC
                FOR EACH ROW
                DECLARE
                    v_action VARCHAR2(20);
                    v_id NUMBER;
                    v_details VARCHAR2(4000);
                BEGIN
                    IF INSERTING THEN
                        v_action := 'INSERT';
                        v_id := :NEW.USER_ID;
                        v_details := 'User created: ' || :NEW.USERNAME;
                    ELSIF UPDATING THEN
                        v_action := 'UPDATE';
                        v_id := :NEW.USER_ID;
                        v_details := 'User updated. Old role: ' || :OLD.ROLE || ', New role: ' || :NEW.ROLE;
                    ELSIF DELETING THEN
                        v_action := 'DELETE';
                        v_id := :OLD.USER_ID;
                        v_details := 'User deleted: ' || :OLD.USERNAME;
                    END IF;

                    INSERT INTO SYSTEM_LOGS (TABLE_NAME, ACTION_TYPE, RECORD_ID, DETAILS)
                    VALUES ('USERS_PUBLIC', v_action, v_id, v_details);
                END;`
            },
            {
                name: 'TRG_LOG_DONATIONS',
                sql: `
                CREATE OR REPLACE TRIGGER TRG_LOG_DONATIONS
                AFTER INSERT OR UPDATE OR DELETE ON DONATIONS
                FOR EACH ROW
                DECLARE
                    v_action VARCHAR2(20);
                    v_id NUMBER;
                    v_details VARCHAR2(4000);
                BEGIN
                    IF INSERTING THEN
                        v_action := 'INSERT';
                        v_id := :NEW.DONATION_ID;
                        v_details := 'Donation created of amount: ' || :NEW.AMOUNT;
                    ELSIF UPDATING THEN
                        v_action := 'UPDATE';
                        v_id := :NEW.DONATION_ID;
                        v_details := 'Donation status changed from ' || :OLD.STATUS || ' to ' || :NEW.STATUS;
                    ELSIF DELETING THEN
                        v_action := 'DELETE';
                        v_id := :OLD.DONATION_ID;
                        v_details := 'Donation deleted';
                    END IF;

                    INSERT INTO SYSTEM_LOGS (TABLE_NAME, ACTION_TYPE, RECORD_ID, DETAILS)
                    VALUES ('DONATIONS', v_action, v_id, v_details);
                END;`
            },
            {
                name: 'TRG_LOG_BENEFICIARIES',
                sql: `
                CREATE OR REPLACE TRIGGER TRG_LOG_BENEFICIARIES
                AFTER INSERT OR UPDATE OR DELETE ON BENEFICIARIES
                FOR EACH ROW
                DECLARE
                    v_action VARCHAR2(20);
                    v_id NUMBER;
                    v_details VARCHAR2(4000);
                BEGIN
                    IF INSERTING THEN
                        v_action := 'INSERT';
                        v_id := :NEW.BENEFICIARY_ID;
                        v_details := 'Beneficiary application created for Region: ' || :NEW.REGION;
                    ELSIF UPDATING THEN
                        v_action := 'UPDATE';
                        v_id := :NEW.BENEFICIARY_ID;
                        v_details := 'Beneficiary status changed from ' || :OLD.ELIGIBILITY_STATUS || ' to ' || :NEW.ELIGIBILITY_STATUS;
                    ELSIF DELETING THEN
                        v_action := 'DELETE';
                        v_id := :OLD.BENEFICIARY_ID;
                        v_details := 'Beneficiary application deleted';
                    END IF;

                    INSERT INTO SYSTEM_LOGS (TABLE_NAME, ACTION_TYPE, RECORD_ID, DETAILS)
                    VALUES ('BENEFICIARIES', v_action, v_id, v_details);
                END;`
            }
        ];

        for (const t of triggers) {
            console.log(`Creating trigger ${t.name}...`);
            await connection.execute(t.sql);
            console.log(`Trigger ${t.name} created.`);
        }

    } catch (err) {
        console.error('Error:', err);
    } finally {
        if (connection) {
            try {
                await connection.close();
            } catch (err) {
                console.error(err);
            }
        }
    }
}

run();
