-- ============================================================
-- SYSTEM LOGS & AUDITING
-- ============================================================

-- 1. Create Logs Table
CREATE TABLE SYSTEM_LOGS (
    LOG_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TABLE_NAME VARCHAR2(50) NOT NULL,
    ACTION_TYPE VARCHAR2(20) NOT NULL, -- INSERT, UPDATE, DELETE
    RECORD_ID NUMBER,
    ACTION_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DETAILS VARCHAR2(4000)
);

-- 2. Triggers

-- Trigger for USERS_PUBLIC
CREATE OR REPLACE TRIGGER TRG_LOG_USERS
AFTER INSERT OR UPDATE OR DELETE ON USERS_PUBLIC
FOR EACH ROW
DECLARE
    v_action VARCHAR2(20);
    v_id NUMBER;
    v_details VARCHAR2(4000);
BEGIN
    IF INSERTING THEN
        v_action := 'INSERT';
        v_id := :NEW.USER_ID;
        v_details := 'User created: ' || :NEW.USERNAME;
    ELSIF UPDATING THEN
        v_action := 'UPDATE';
        v_id := :NEW.USER_ID;
        v_details := 'User updated. Old role: ' || :OLD.ROLE || ', New role: ' || :NEW.ROLE;
    ELSIF DELETING THEN
        v_action := 'DELETE';
        v_id := :OLD.USER_ID;
        v_details := 'User deleted: ' || :OLD.USERNAME;
    END IF;

    INSERT INTO SYSTEM_LOGS (TABLE_NAME, ACTION_TYPE, RECORD_ID, DETAILS)
    VALUES ('USERS_PUBLIC', v_action, v_id, v_details);
END;
/

-- Trigger for DONATIONS
CREATE OR REPLACE TRIGGER TRG_LOG_DONATIONS
AFTER INSERT OR UPDATE OR DELETE ON DONATIONS
FOR EACH ROW
DECLARE
    v_action VARCHAR2(20);
    v_id NUMBER;
    v_details VARCHAR2(4000);
BEGIN
    IF INSERTING THEN
        v_action := 'INSERT';
        v_id := :NEW.DONATION_ID;
        v_details := 'Donation created of amount: ' || :NEW.AMOUNT;
    ELSIF UPDATING THEN
        v_action := 'UPDATE';
        v_id := :NEW.DONATION_ID;
        v_details := 'Donation status changed from ' || :OLD.STATUS || ' to ' || :NEW.STATUS;
    ELSIF DELETING THEN
        v_action := 'DELETE';
        v_id := :OLD.DONATION_ID;
        v_details := 'Donation deleted';
    END IF;

    INSERT INTO SYSTEM_LOGS (TABLE_NAME, ACTION_TYPE, RECORD_ID, DETAILS)
    VALUES ('DONATIONS', v_action, v_id, v_details);
END;
/

-- Trigger for BENEFICIARIES
CREATE OR REPLACE TRIGGER TRG_LOG_BENEFICIARIES
AFTER INSERT OR UPDATE OR DELETE ON BENEFICIARIES
FOR EACH ROW
DECLARE
    v_action VARCHAR2(20);
    v_id NUMBER;
    v_details VARCHAR2(4000);
BEGIN
    IF INSERTING THEN
        v_action := 'INSERT';
        v_id := :NEW.BENEFICIARY_ID;
        v_details := 'Beneficiary application created for Region: ' || :NEW.REGION;
    ELSIF UPDATING THEN
        v_action := 'UPDATE';
        v_id := :NEW.BENEFICIARY_ID;
        v_details := 'Beneficiary status changed from ' || :OLD.ELIGIBILITY_STATUS || ' to ' || :NEW.ELIGIBILITY_STATUS;
    ELSIF DELETING THEN
        v_action := 'DELETE';
        v_id := :OLD.BENEFICIARY_ID;
        v_details := 'Beneficiary application deleted';
    END IF;

    INSERT INTO SYSTEM_LOGS (TABLE_NAME, ACTION_TYPE, RECORD_ID, DETAILS)
    VALUES ('BENEFICIARIES', v_action, v_id, v_details);
END;
/
